GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjQ1NTk0MTczfQ.peKF-bsJ6CescULhf1iYuXxXwaPZMtKqfS6GVfVatgI

###
// API 1
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###
// API 2
POST http://localhost:3000/login
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###

// API 3

GET http://localhost:3000/user/tweets/feed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjQ1NTQwNjQ4fQ.6yYPBGImma-JZ865im4r0URuIX3cbcNz9yGcU59iNuo

###

// API 4 

GET http://localhost:3000/user/following
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjQ1NTQwNjQ4fQ.6yYPBGImma-JZ865im4r0URuIX3cbcNz9yGcU59iNuo

###


// API 5 
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjQ1NTQwNjQ4fQ.6yYPBGImma-JZ865im4r0URuIX3cbcNz9yGcU59iNuo

###

// API 6

GET http://localhost:3000/tweets/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjQ1NTQwNjQ4fQ.6yYPBGImma-JZ865im4r0URuIX3cbcNz9yGcU59iNuo


####

// API 9

GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjQ1NTQwNjQ4fQ.6yYPBGImma-JZ865im4r0URuIX3cbcNz9yGcU59iNuo



###


// API 10

POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjQ1NTQwNjQ4fQ.6yYPBGImma-JZ865im4r0URuIX3cbcNz9yGcU59iNuo
Content-Type: application/json

{
   "tweet": "The Mornings..."
}



###

// API 11
 

DELETE http://localhost:3000/tweets/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjQ1NTQwNjQ4fQ.6yYPBGImma-JZ865im4r0URuIX3cbcNz9yGcU59iNuo